title: iNUX Interactive Documents
description: An overview about iNUX Jupyter Notebooks and Streamlit Apps for interactive education
theme: just-the-docs

url: https://gw-inux.github.io/iNUX-Interactive-Documents

aux_links:
  Template Repository: https://github.com/gw-inux/iNUX-Interactive-Documents
  
sass:
    sass_dir: _sass
    style: compressed

color_scheme: iNUX_colors1
#logo: "/assets/images/iNUX_wLogo.png"